"""Static type contract shared by :class:`GameState` and its mixins (#3030).

``GameState`` (``game/state.py``) is assembled from fourteen ``state_*.py``
mixins. Each mixin reads attributes that ``GameState.__init__`` (or
``_apply_config`` / ``create_game``) sets and calls methods that live on a
*sibling* mixin, but none of them used to say so — mypy saw a bare class with
none of those names and reported hundreds of ``attr-defined`` errors, which is
why the mixins were kept out of the ``[tool.mypy] files`` gate (#1275).

:class:`GameStateContract` is that missing declaration: the attributes shared
across more than one class, the config-applied fields, and the signatures of
every method or property one class calls on another. Each mixin inherits from
:data:`GameStateBase`, so mypy checks every ``self.*`` access against this
contract, and an override in a mixin is checked against the declared
signature.

**Type-checking only.** The contract exists solely under ``TYPE_CHECKING``; at
runtime :data:`GameStateBase` is plain ``object``, so ``class
PauseResumeMixin(GameStateBase)`` is exactly ``class PauseResumeMixin:`` — no
new class in the MRO, no class attributes that could shadow instance state, no
import back into ``state.py``. Nothing here executes.

Keep it in step: a new cross-mixin attribute or method call belongs here, and
a signature change in a mixin has to be mirrored below (mypy reports the
mismatch as an incompatible override).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import asyncio
    from collections.abc import Awaitable, Callable
    from typing import Any

    from homeassistant.core import HomeAssistant

    from custom_components.beatify.services.stats import StatsService

    from .challenges import ArtistChallenge, ChallengeManager, MovieChallenge
    from .config import GameStateConfig
    from .highlights import HighlightsTracker
    from .player import PlayerSession
    from .player_registry import PlayerRegistry
    from .playlist import PlaylistManager
    from .powerups import PowerUpManager
    from .protocols import (
        GameOutputFactories,
        MediaPlayerProtocol,
        PartyLightsProtocol,
        TtsProtocol,
    )
    from .round_manager import RoundManager
    from .state import GamePhase
    from .types import RoundAnalytics

    class GameStateContract:
        """Everything the mixins expect to find on ``self`` (#3030)."""

        # --- Owned subsystems and injected services (GameState.__init__)
        _now: Callable[[], float]
        _service_factories: GameOutputFactories
        _hass: HomeAssistant | None
        _player_registry: PlayerRegistry
        _round_manager: RoundManager
        _powerup_manager: PowerUpManager
        _challenge_manager: ChallengeManager
        _playlist_manager: PlaylistManager | None
        _media_player_service: MediaPlayerProtocol | None
        _party_lights: PartyLightsProtocol | None
        _tts_service: TtsProtocol | None
        _stats_service: StatsService | None
        highlights_tracker: HighlightsTracker
        _default_config: GameStateConfig

        # --- Game identity and phase
        game_id: str | None
        admin_token: str | None
        rematched_from_game_id: str | None
        _game_epoch: int
        phase: GamePhase
        reveal_started_at: int | None

        # --- Tasks, locks and callbacks
        _auto_advance_task: asyncio.Task | None
        _prewarm_task: asyncio.Task | None
        _bg_tasks: set[asyncio.Task]
        _score_lock: asyncio.Lock
        _on_round_end: Callable[[], Awaitable[None]] | None
        _on_game_end: Callable[[], Awaitable[None]] | None
        pre_start_hook: Callable[[Any], Awaitable[None]] | None

        # --- Title & Artist vote window and pause snapshot
        _title_artist_voting_open: bool
        _title_artist_vote_deadline: float | None
        _paused_vote_open: bool
        _paused_vote_deadline: float | None
        _paused_round_remaining_ms: int | None
        _paused_at: float | None
        _paused_clock_unstarted: bool

        # --- Round bookkeeping set by more than one mixin
        _consecutive_playback_failures: int
        _encore_window: bool
        _returned_this_round: list[str]
        _finale_playoff_rounds: int
        _finale_playoff_active: bool
        comeback_granted_this_round: list[str]
        _tts_pre_round_delay: float

        # --- Output settings
        _pending_speaker_states: dict[str, dict[str, Any]]
        party_lights_config: dict[str, Any] | None
        volume_level: float
        platform: str
        storefront: str | None
        max_rounds: int
        reveal_auto_advance: int

        # --- GameStateConfig fields, set by _apply_config via setattr
        playlists: list[str]
        songs: list[dict[str, Any]]
        media_player: str
        join_url: str
        provider: str
        difficulty: str
        language: str
        pause_reason: str | None
        _previous_phase: GamePhase | None
        disconnected_admin_name: str | None
        last_error_detail: str
        closest_wins_mode: bool
        rampup_order_enabled: bool
        sudden_death_mode: bool
        finale_double_enabled: bool
        finale_tiebreaker_enabled: bool
        comeback_token_enabled: bool
        difficulty_bet_scaling_enabled: bool
        sabotage_enabled: bool

        # --- Methods and properties called across classes, by owner
        # GameState (state.py)
        def _apply_config(self, config: GameStateConfig) -> None: ...
        def _apply_sudden_death_elimination(self) -> list[str]: ...
        async def _end_round_unlocked(self) -> None: ...
        async def _fetch_metadata_async(self, uri: str) -> None: ...
        def _maybe_grant_comeback_tokens(self) -> list[str]: ...
        def _notify_reset_callbacks(self) -> None: ...
        def _notify_state_callbacks(self) -> None: ...
        def _schedule_song_end_auto_advance(self) -> None: ...
        def _score_all_players(
            self, correct_year: int | None, all_players: list[PlayerSession]
        ) -> None: ...
        def _set_phase(
            self, new_phase: GamePhase, *, notify: bool = True, restore: bool = False
        ) -> None: ...
        def _title_artist_scoring_deferred(self) -> bool: ...
        def calculate_round_analytics(self) -> RoundAnalytics: ...
        async def end_round(self) -> None: ...
        def non_eliminated_players(self) -> list[PlayerSession]: ...

        # ChallengeMixin
        @property
        def artist_challenge(self) -> ArtistChallenge | None: ...
        @artist_challenge.setter
        def artist_challenge(self, value: ArtistChallenge | None) -> None: ...
        @property
        def artist_challenge_enabled(self) -> bool: ...
        @artist_challenge_enabled.setter
        def artist_challenge_enabled(self, value: bool) -> None: ...
        def get_near_misses(self) -> list[dict[str, Any]]: ...
        def has_near_misses(self) -> bool: ...
        @property
        def movie_challenge(self) -> MovieChallenge | None: ...
        @movie_challenge.setter
        def movie_challenge(self, value: MovieChallenge | None) -> None: ...
        @property
        def movie_quiz_enabled(self) -> bool: ...
        @movie_quiz_enabled.setter
        def movie_quiz_enabled(self, value: bool) -> None: ...
        @property
        def title_artist_challenge(self) -> Any: ...
        @title_artist_challenge.setter
        def title_artist_challenge(self, value: Any) -> None: ...
        @property
        def title_artist_mode(self) -> bool: ...
        @title_artist_mode.setter
        def title_artist_mode(self, value: bool) -> None: ...

        # LeaderboardMixin
        def _store_previous_ranks(self) -> None: ...
        def get_final_leaderboard(self) -> list[dict[str, Any]]: ...

        # MediaControlMixin
        async def _lights_flash(self, color: str) -> None: ...
        async def _lights_set_phase(self, phase: GamePhase) -> None: ...
        async def disable_party_lights(self) -> None: ...
        async def play_deferred_song(self, song: dict) -> bool: ...
        async def restore_player_queue(self) -> bool: ...
        async def restore_player_volume(self) -> bool: ...
        async def stop_media(self) -> None: ...

        # PauseResumeMixin
        async def pause_game(self, reason: str) -> bool: ...

        # PlayerLifecycleMixin
        def all_submitted(self) -> bool: ...
        def apply_pending_rejoins(self) -> list[str]: ...
        @property
        def bet_tracking(self) -> dict[str, int]: ...
        @bet_tracking.setter
        def bet_tracking(self, value: dict[str, int]) -> None: ...
        def clear_all_sessions(self) -> None: ...
        @property
        def players(self) -> dict[str, PlayerSession]: ...
        @players.setter
        def players(self, value: dict[str, PlayerSession]) -> None: ...
        @property
        def streak_achievements(self) -> dict[str, int]: ...
        @streak_achievements.setter
        def streak_achievements(self, value: dict[str, int]) -> None: ...

        # RevealAutoAdvanceMixin
        def _cancel_auto_advance(self) -> None: ...
        async def _reveal_auto_advance(self, timer_seconds: int) -> None: ...
        async def _reveal_idle_halt(self) -> None: ...

        # RevealTransitionMixin
        async def _apply_reveal_lights(self, correct_year: int | None) -> None: ...
        async def _timer_countdown(self, delay_seconds: float) -> None: ...
        async def _transition_to_reveal(self, correct_year: int | None) -> None: ...
        async def advance_to_end(self) -> None: ...
        def cancel_timer(self) -> None: ...
        async def confirm_intro_splash(self) -> None: ...

        # RoundLifecycleMixin
        def _cancel_prewarm(self) -> None: ...
        def _ensure_media_player_service(self) -> None: ...
        def schedule_media_player_prewarm(self) -> None: ...
        async def start_round(self, _retry_count: int = 0) -> bool: ...

        # RoundManagerDelegationMixin
        @property
        def current_song(self) -> dict[str, Any] | None: ...
        @current_song.setter
        def current_song(self, value: dict[str, Any] | None) -> None: ...
        @property
        def deadline(self) -> int | None: ...
        @deadline.setter
        def deadline(self, value: int | None) -> None: ...
        @property
        def intro_mode_enabled(self) -> bool: ...
        @intro_mode_enabled.setter
        def intro_mode_enabled(self, value: bool) -> None: ...
        @property
        def intro_splash_pending(self) -> bool: ...
        @property
        def intro_stopped(self) -> bool: ...
        @intro_stopped.setter
        def intro_stopped(self, value: bool) -> None: ...
        @property
        def is_intro_round(self) -> bool: ...
        @is_intro_round.setter
        def is_intro_round(self, value: bool) -> None: ...
        @property
        def last_round(self) -> bool: ...
        @last_round.setter
        def last_round(self, value: bool) -> None: ...
        @property
        def metadata_pending(self) -> bool: ...
        @metadata_pending.setter
        def metadata_pending(self, value: bool) -> None: ...
        @property
        def round(self) -> int: ...
        @round.setter
        def round(self, value: int) -> None: ...
        @property
        def round_analytics(self) -> RoundAnalytics | None: ...
        @round_analytics.setter
        def round_analytics(self, value: RoundAnalytics | None) -> None: ...
        @property
        def round_duration(self) -> float: ...
        @round_duration.setter
        def round_duration(self, value: float) -> None: ...
        @property
        def round_start_time(self) -> float | None: ...
        @round_start_time.setter
        def round_start_time(self, value: float | None) -> None: ...
        @property
        def round_voided(self) -> bool: ...
        @round_voided.setter
        def round_voided(self, value: bool) -> None: ...
        @property
        def song_stopped(self) -> bool: ...
        @song_stopped.setter
        def song_stopped(self, value: bool) -> None: ...
        @property
        def songs_remaining(self) -> int: ...
        @property
        def total_rounds(self) -> int: ...
        @total_rounds.setter
        def total_rounds(self, value: int) -> None: ...
        @property
        def void_reason(self) -> str | None: ...
        @void_reason.setter
        def void_reason(self, value: str | None) -> None: ...
        @property
        def voided_rounds(self) -> list[dict[str, Any]]: ...

        # RoundScoringMixin
        def _append_round_results(self) -> None: ...
        async def _record_round_stats(self, correct_year: int | None) -> None: ...
        def _score_round(self, correct_year: int | None) -> None: ...

        # StateSerializationMixin
        def compute_winners(self) -> tuple[list[PlayerSession], int]: ...
        def get_song_difficulty(self, song_uri: str) -> dict[str, Any] | None: ...

        # TtsAnnouncerMixin
        async def _announce_reveal(self, correct_year: int | None) -> None: ...
        def _init_tts_state(self) -> None: ...
        async def announce_countdown(self) -> None: ...
        async def announce_finale_playoff(self, names: list[str]) -> None: ...
        async def announce_intro_round(self) -> None: ...
        async def announce_last_round(self) -> None: ...
        async def announce_podium(self) -> None: ...
        async def announce_round_start(self) -> None: ...
        async def announce_time_up(self) -> None: ...
        async def announce_winner(self) -> None: ...
        async def disable_tts(self) -> None: ...

        # VoteWindowMixin
        async def _finalize_title_artist_window(self) -> None: ...
        def _schedule_title_artist_vote_window(self) -> None: ...
        async def _title_artist_vote_window(self, window_seconds: float) -> None: ...

    GameStateBase = GameStateContract
else:
    GameStateBase = object
