"""Crate Digger — regression guards for bugs found on real hardware.

Every check here corresponds to a defect that shipped and was diagnosed on a
live Home Assistant with Music Assistant voice satellites, an Android TV and
an Echo. They are deliberately structural (they read the source) because the
behaviour they protect involves device timing that a unit test cannot
reproduce — the alternative to a source guard is no guard at all.

Where a bug IS reproducible in pure logic it is tested properly instead; see
test_library_generator.py and test_library_metadata.py.
"""

from __future__ import annotations

from pathlib import Path

import pytest

COMPONENT = Path(__file__).resolve().parents[2] / "custom_components" / "beatify"


def src(relative: str) -> str:
    return (COMPONENT / relative).read_text(encoding="utf-8")


class TestSettingsReachTheGameTheyWereSetFor:
    """The off-by-one family: settings applying one game late.

    A room freezes its parameters at creation, but the lobby's reset button
    creates the next room immediately — so anything changed afterwards missed
    its own game. Songs are regenerated by a pre-start hook; device, TTS and
    party lights are re-applied from a server-side Store.
    """

    def test_pre_start_hook_fires_from_start_round(self):
        """Not from the REST view: the websocket admin path bypasses it.

        Hooking the view fixed the bug for one start path and left it live on
        the other, which is how this bug survived a correct-looking fix.
        """
        code = src("game/state_lifecycle.py")
        assert "pre_start_hook" in code
        assert "self.pre_start_hook = None" in code, "must fire once per game"

    def test_library_games_install_the_hook(self):
        assert "pre_start_hook = _regen_library_songs" in src("server/game_views.py")

    def test_output_settings_are_persisted_and_re_applied(self):
        assert "async_save_game_output_settings" in src("server/library_views.py")
        assert "async_load_game_output_settings" in src("server/game_views.py")

    def test_reset_clears_the_persisted_output_settings(self):
        """Upstream's reset is installation-wide (#2036); ours must follow,
        or the pre-start re-apply would restore pre-reset settings."""
        assert "async_clear_game_output_settings" in src("server/game_views.py")

    def test_device_switch_drops_the_cached_media_service(self):
        """#2143 changed HOW it is dropped, not THAT it is dropped.

        The service must still go — it captures entity and platform at
        construction, so keeping it routes playback to the old device. But
        nulling the reference outright also dropped the old speaker's pre-game
        volume (#1516) and queue (#2143). `release_media_player_service`
        preserves those and then nulls. A bare `= None` here is the regression.
        """
        code = src("server/game_views.py")
        assert "release_media_player_service()" in code
        assert "_media_player_service = None" not in code

    def test_device_switch_supersedes_the_lobby_prewarm(self):
        """#1540 pre-warms the service with the entity chosen at CREATE; a
        pre-warm landing after a switch would reinstate the old speaker."""
        code = src("server/game_views.py")
        assert "_cancel_prewarm" in code and "schedule_media_player_prewarm" in code


class TestServiceLifecycle:
    def test_create_game_resets_tts_and_lights_services(self):
        """A new game with TTS disabled kept announcing on the PREVIOUS
        game's speaker, because configure_tts is only called when a config is
        supplied and nothing cleared the stale service."""
        code = src("game/state_setup.py")
        assert "self._tts_service = None" in code
        assert "self._party_lights = None" in code

    def test_configs_are_unpacked_not_passed_as_raw_dicts(self):
        """configure_tts takes an ENTITY ID; configure_party_lights takes a
        LIST. Passing the frontend dicts was accepted silently, then crashed
        inside speak() and made "4 lights" out of four config keys."""
        code = src("server/game_views.py")
        assert "_apply_tts_config" in code and "_apply_party_lights_config" in code
        assert 'tts_config.get("entity_id", "")' in code
        assert 'cfg.get("entity_ids")' in code

    def test_explicit_disable_is_distinguished_from_absent(self):
        code = src("server/game_views.py")
        assert "disable_tts()" in code and "disable_party_lights()" in code


class TestAnnouncementsAndPlayback:
    """Announcements interrupt playback; several bugs came from that."""

    def test_announcements_are_serialized_with_staleness_dropping(self):
        """Fire-and-forget announcements let MA's per-player queue run behind
        the game: the previous round's "time's up" played after the next
        round had started."""
        code = src("game/state_tts.py")
        assert "_announce_lock" in code
        assert "dropping stale announcement" in code

    def test_staleness_keys_on_the_round_not_the_phase(self):
        """Keying on phase too swallowed every end-of-round announcement:
        those fire exactly AS the phase changes PLAYING -> REVEAL."""
        code = src("game/state_tts.py")
        assert "phase_at_enqueue" not in code

    def test_the_speaker_window_is_reserved_at_enqueue(self):
        """Everything that asks "is the speaker busy?" runs immediately after
        the announcements are fired, so reserving the window only once speech
        BEGINS reads as zero to all of them — the watchdog's anticipatory
        kick never fired on hardware for exactly this reason."""
        code = src("game/state_tts.py")
        assert 'start_at = max(now, getattr(self, "_announce_busy_until", 0.0))' in code
        assert "self._announce_busy_until = start_at + est" in code

    def test_a_dropped_announcement_releases_its_reservation(self):
        code = src("game/state_tts.py")
        assert "self._announce_busy_until = start_at" in code

    def test_playback_waits_for_a_busy_speaker(self):
        """Starting a song while announcements drain made play_song's
        verification window watch an announcement, time out, and drop the
        song — the "skips only with TTS on" report."""
        code = src("game/state_lifecycle.py")
        assert "announcement_busy_seconds" in code

    def test_the_wait_is_bounded(self):
        assert "8.0)" in src("game/state_lifecycle.py")

    def test_round_deadline_accounts_for_announcements(self):
        """A 60s round reached the music with ~49s left."""
        code = src("game/state_lifecycle.py")
        assert "estimate_round_start_announcements" in code

    def test_resume_watchdog_retains_its_task(self):
        """asyncio holds only WEAK references: an unreferenced task was
        garbage-collected before running, so the watchdog produced no log
        lines at all for three releases."""
        assert "self._tts_resume_task = _asyncio.create_task" in src(
            "game/state_lifecycle.py"
        )

    def test_resume_watchdog_triggers_on_idle_not_only_paused(self):
        """MA voice satellites stick in 'idle' with a title loaded; HA never
        reports 'paused' for them."""
        assert "idle_streak >= 2" in src("game/state_lifecycle.py")

    def test_announcement_is_not_mistaken_for_a_song_ending(self):
        """With auto-advance "Off" (= advance at song end), an announcement
        interruption read as a finished song and skipped the round."""
        code = src("game/state_auto_advance.py")
        assert "announcement_busy_seconds" in code
        assert "_ANNOUNCE_RESUME_GRACE" in code

    def test_each_round_replaces_the_playback_queue(self):
        """Without enqueue=replace, rounds accumulated in MA's queue and a
        post-announcement resume advanced into earlier rounds' songs."""
        assert '"enqueue": "replace"' in src("services/media_player.py")


class TestPlaybackWiring:
    def test_library_uri_field_survives_rebases(self):
        """This branch has been silently dropped by a rebase before; without
        it every library game resolves no URIs at all."""
        code = src("game/playlist.py")
        assert "uri_ma_library" in code
        assert "PROVIDER_MA_LIBRARY" in code

    def test_library_provider_is_declared_playable(self):
        assert '"ma_library"' in src("services/media_player.py")

    def test_stale_uris_fall_back_to_a_name_lookup(self):
        """Library item ids change when a library is rebuilt.

        The log line used to read "MA library fallback". It now reads
        "MA name fallback (<provider>)" because Tidal shares the path, so this
        asserts on the guard that actually decides whether the fallback runs
        instead of on the wording of a log message.
        """
        code = src("services/media_player.py")
        assert "_NAME_FALLBACK_PROVIDERS" in code
        assert '"ma_library"' in code
        assert "MA name fallback" in code


class TestWizardIntegration:
    def test_library_step_restores_the_wizard_navigation(self):
        """Upstream hides the CTA band on frame 3 because the Playlist Hub
        supplies its own Back/Continue. Crate Digger has no hub, so without
        this body flag the step has no navigation at all."""
        assert "wiz-lib-step" in src("www/js/wizard.js")
        assert "wiz-lib-step" in src("www/css/library.css")

    def test_the_flag_is_cleared_when_leaving_the_step(self):
        assert "classList.remove('wiz-lib-step')" in src("www/js/wizard.js")

    def test_provider_entry_explains_what_it_plays(self):
        """ "Crate Digger" alone doesn't tell a new host that this is their
        own library."""
        code = src("www/js/wizard.js")
        assert "wizard.providerLibrarySub" in code
        assert "wiz-provider-sub" in src("www/css/library.css")


class TestSetupCompleteness:
    """Crate Digger selects no playlist — the library IS the source.

    Both the server flag and the client fallback required a non-empty
    playlist list, so a host who had finished the wizard was told "You
    haven't set up yet" and the home view read "no playlist".
    """

    def test_library_setup_is_complete_without_a_playlist(self):
        from custom_components.beatify.server.serializers import _is_setup_complete

        assert (
            _is_setup_complete(
                {
                    "last_player": "media_player.kitchen",
                    "game_settings": {"selectedProvider": "ma_library"},
                }
            )
            is True
        )

    def test_the_in_memory_alias_is_also_accepted(self):
        from custom_components.beatify.server.serializers import _is_setup_complete

        assert (
            _is_setup_complete(
                {
                    "last_player": "media_player.kitchen",
                    "game_settings": {"selectedProvider": "ma_library"},
                }
            )
            is True
        )

    def test_other_providers_still_require_a_playlist(self):
        from custom_components.beatify.server.serializers import _is_setup_complete

        assert (
            _is_setup_complete(
                {
                    "last_player": "media_player.kitchen",
                    "game_settings": {"provider": "spotify"},
                }
            )
            is False
        )

    def test_a_speaker_is_still_required(self):
        from custom_components.beatify.server.serializers import _is_setup_complete

        assert (
            _is_setup_complete({"game_settings": {"selectedProvider": "ma_library"}})
            is False
        )

    def test_client_fallback_matches_the_server_rule(self):
        code = src("www/js/admin.js")
        # Source syntax, checked in the SOURCE file — variable names do not
        # survive minification, so bundle checks use string constants only.
        assert "(s.provider || s.selectedProvider) === 'ma_library'" in code
        assert "libraryPlaylistLabel" in code


class TestCreateGameAcceptsAGeneratingProvider:
    """Upstream assumes every game selects a playlist.

    That assumption is encoded in four separate places, each of which had to
    be taught about a provider that GENERATES its source: the wizard chrome,
    the setup-complete flag, the home summary, and this — the create-game
    guard, which rejected the request outright with "No playlists selected"
    before the library branch could run.
    """

    def test_the_playlist_guard_exempts_the_library_provider(self):
        code = src("server/game_views.py")
        assert "if not playlist_paths and provider != PROVIDER_MA_LIBRARY:" in code

    def test_the_guard_still_applies_to_every_other_provider(self):
        code = src("server/game_views.py")
        assert '"No playlists selected"' in code

    def test_provider_is_validated_before_the_guard_uses_it(self):
        """Order matters: the guard compares `provider`, so validation must
        already have normalised it."""
        code = src("server/game_views.py")
        assert code.index("provider = _validate_provider(provider)") < code.index(
            "if not playlist_paths and provider != PROVIDER_MA_LIBRARY:"
        )

    def test_an_empty_generated_playlist_is_still_rejected(self):
        """A library game whose generation yielded nothing must fail loudly
        rather than create an unplayable room."""
        assert '"No valid songs found in selected playlists"' in src(
            "server/game_views.py"
        )


class TestProviderIsAccepted:
    """The root cause of "Cannot start — No playlists selected".

    `_validate_provider` coerces anything not in its whitelist to the default
    provider. `ma_library` was missing, so the selection silently became
    Spotify BEFORE the playlist guard ran — the exemption never matched, the
    request 400'd in ~4ms, and nothing was logged because validation precedes
    every log line. The function's own docstring records the identical
    failure for Apple Music (#808).
    """

    def test_the_library_provider_is_whitelisted(self):
        from custom_components.beatify.server.game_views import _validate_provider

        assert _validate_provider("ma_library") == "ma_library"

    def test_unknown_providers_are_still_coerced(self):
        from custom_components.beatify.server.game_views import _validate_provider

        assert _validate_provider("napster") != "napster"

    def test_players_advertise_library_support(self):
        """The wizard greys out providers a speaker can't play; without this
        flag Crate Digger would be offered on speakers that cannot serve it."""
        assert '"supports_ma_library"' in src("services/media_player.py")


class TestRoundClockStartsWithTheMusic:
    """The countdown must measure MUSIC, not announcements.

    Round-start announcements run between initialize_round and the first
    audible note. Estimating their cost (0.7.29) helped but degrades as
    rounds shorten — a 15s round with a spoken round number and a countdown
    leaves under 7 seconds of song. Upstream already solved the same problem
    for intro splashes (#1699) by re-stamping the deadline when the deferred
    song plays; this applies that pattern to announcements.
    """

    def test_the_deadline_can_be_deferred(self):
        code = src("game/round_manager.py")
        assert "_deadline_deferred" in code
        assert "def defer_deadline" in code

    def test_a_deferred_deadline_never_reads_as_passed(self):
        code = src("game/round_manager.py")
        assert "if self._intro_splash_pending or self._deadline_deferred:" in code

    def test_the_clock_restarts_when_playback_begins(self):
        code = src("game/round_manager.py")
        assert "def start_timer_at_playback" in code

    def test_restamping_is_idempotent(self):
        """A provider that never announces must be unaffected."""
        code = src("game/round_manager.py")
        assert "if not self._deadline_deferred:\n            return" in code

    def test_clients_are_told_about_the_new_deadline(self):
        assert "_notify_state_callbacks()" in src("game/state_lifecycle.py")


class TestVolumeRatchetGuard:
    def test_an_upward_drift_across_an_announcement_is_undone(self):
        """MA's announce duck/restore wrote back a HIGHER level each round on
        a ShieldTV feeding an AV receiver — painfully loud within a few
        rounds."""
        code = src("game/state_lifecycle.py")
        assert "_vol_before" in code and "volume_set" in code

    def test_the_guard_fires_once_and_only_during_the_announcement_window(self):
        """The host's own volume buttons must keep working."""
        code = src("game/state_lifecycle.py")
        assert "not vol_restored" in code and "tick <= 10" in code


class TestClientClockIndependence:
    def test_state_carries_the_server_clock(self):
        """A device ~20s off showed "20s remaining" at the moment the server
        declared time-up. The round counter is deadline-driven, so it needs
        the server clock to correct for skew."""
        assert 'state["server_now_ms"]' in src("game/serializers.py")

    def test_admin_countdown_corrects_for_skew(self):
        assert "clockSkewMs" in src("www/js/admin.js")


class TestShippedBundles:
    """`.min.js` drift is invisible until a user reports a missing feature."""

    @pytest.mark.parametrize(
        "needle",
        [
            "library-pool/preview",  # live match count
            "library-pool/backup",  # backup button
            "library-pool/restore",  # restore button
            "update-lobby",  # settings pushes
            "server_now_ms",  # skew-corrected countdown
        ],
    )
    def test_library_ui_is_present_in_the_admin_bundle(self, needle):
        assert needle in src("www/js/admin.min.js")


class TestImportHygiene:
    """Module names used via attribute access need a module-level import.

    A missing `import contextlib` — masked because an unrelated function had
    a local aliased import — killed an endpoint mid-handler and strangled
    three architecturally correct fixes across as many releases.
    """

    @pytest.mark.parametrize(
        ("path", "module"),
        [
            ("server/game_views.py", "contextlib"),
            ("server/library_views.py", "json"),
            ("game/state_auto_advance.py", "time"),
            ("game/state_tts.py", "time"),
        ],
    )
    def test_module_level_import_present_where_used(self, path, module):
        code = src(path)
        if f"{module}." not in code:
            pytest.skip(f"{module} not used in {path}")
        assert any(line.strip() == f"import {module}" for line in code.splitlines()), (
            f"{path} uses {module}. without a module-level import"
        )
